#!/usr/bin/env python3
"""Learning history: one markdown file per learning in docs/learnings/entries/.

Stdlib only, no YAML dependency. The only writer of entries (see docs/learnings/SCHEMA.md).

Usage:
    python3 learnings.py match  --category C --failure-mode M --asset-path P --asset-section S
    python3 learnings.py record --slug SLUG --category C ... --spec SPEC --increment N ...
    python3 learnings.py record --slug SLUG [--fixed-by B --fix-target T --fix-why W --fixed-at D] [--fix-pr URL]
    python3 learnings.py index
    python3 learnings.py check

Every subcommand takes --docs-root (default: docs/learnings).
"""

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

FAILURE_MODES: Dict[str, Tuple[str, ...]] = {
    "asset_interpretation_gaps": (
        "agents_md_not_followed",
        "skill_unexpected_behavior",
        "standard_not_followed",
        "workflow_not_followed",
    ),
    "bad_expectation": (
        "skill_false_trigger",
        "skill_missed_trigger",
        "agents_md_degrades",
        "ontology_degrades",
        "spec_corrected_midflight",
    ),
    "time_cost": ("task_too_long", "task_looping"),
    "side_improvement": ("adr", "lint_hook", "observability", "principle"),
}
STATUSES = ("detected", "fixed")
KEY_FIELDS = ("category", "failure_mode", "asset_path", "asset_section")
REQUIRED_FIELDS = KEY_FIELDS + ("symptom", "status")
FIX_FIELDS = ("fixed_by", "fix_target", "fix_why", "fixed_at")
FRONT_MATTER_ORDER = REQUIRED_FIELDS + FIX_FIELDS + ("fix_pr", "backfilled")
OCCURRENCE_FIELDS = ("spec", "increment", "date", "evidence", "discarded_by", "related_to", "related_reason")
OCCURRENCE_REQUIRED = ("spec", "increment", "date")
NO_ASSET = "none"
STATUS_FIXED = "fixed"
STATUS_DETECTED = "detected"
STATUS_RECURRED = "recurred"
EXIT_OK = 0
EXIT_PROBLEMS = 1
SLUG_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
FRONT_LINE_RE = re.compile(r"^([a-z_]+):\s*(.*)$")
OCCURRENCE_PAIR_RE = re.compile(r'([a-z_]+)=("(?:[^"\\]|\\.)*"|\S+)')
BARE_VALUE_RE = re.compile(r"^[\w./#:@-]+$")
DEFAULT_DOCS_ROOT = Path(__file__).resolve().parents[2] / "docs" / "learnings"
INDEX_TITLE = (
    "# Learning history\n\n"
    "Generated by `.agents/scripts/learnings.py index`. Do not edit by hand.\n\n"
)
INDEX_COLUMNS = ("Learning", "Category", "Failure mode", "Target", "Status", "Occurrences", "Last seen")
MIN_COLUMN_WIDTH = 3


class ToolError(Exception):
    pass


@dataclass
class Entry:
    slug: str
    fields: Dict[str, str] = field(default_factory=dict)
    occurrences: List[Dict[str, str]] = field(default_factory=list)

    @property
    def key(self) -> Tuple[str, ...]:
        return tuple(self.fields.get(name, "") for name in KEY_FIELDS)


def allowed_modes_text(category: str) -> str:
    return ", ".join(FAILURE_MODES[category])


def validate_vocabulary(category: str, failure_mode: str) -> None:
    if category not in FAILURE_MODES:
        raise ToolError(f"unknown category '{category}'; allowed: {', '.join(FAILURE_MODES)}")
    if failure_mode not in FAILURE_MODES[category]:
        raise ToolError(
            f"failure_mode '{failure_mode}' does not belong to category '{category}'; "
            f"allowed: {allowed_modes_text(category)}"
        )


def encode_value(value: str) -> str:
    return value if BARE_VALUE_RE.match(value) else json.dumps(value, ensure_ascii=False)


def decode_value(raw: str) -> str:
    return json.loads(raw) if raw.startswith('"') else raw


def single_line(value: str) -> str:
    return " ".join(value.split())


def render_entry(entry: Entry) -> str:
    front = [f"{name}: {single_line(entry.fields[name])}" for name in FRONT_MATTER_ORDER if name in entry.fields]
    lines = ["---", *front, "---", "", "## Occurrences", ""]
    for occurrence in entry.occurrences:
        pairs = [f"{name}={encode_value(occurrence[name])}" for name in OCCURRENCE_FIELDS if occurrence.get(name)]
        lines.append("- " + " ".join(pairs))
    return "\n".join(lines) + "\n"


def parse_entry(slug: str, text: str) -> Entry:
    entry = Entry(slug)
    lines = text.splitlines()
    if not lines or lines[0] != "---" or "---" not in lines[1:]:
        return entry
    closing = lines.index("---", 1)
    for line in lines[1:closing]:
        match = FRONT_LINE_RE.match(line)
        if match:
            entry.fields[match.group(1)] = match.group(2).strip()
    for line in lines[closing + 1 :]:
        if line.startswith("- "):
            entry.occurrences.append(
                {name: decode_value(raw) for name, raw in OCCURRENCE_PAIR_RE.findall(line[2:])}
            )
    return entry


def entries_dir(docs_root: Path) -> Path:
    return docs_root / "entries"


def load_entries(docs_root: Path) -> List[Entry]:
    directory = entries_dir(docs_root)
    if not directory.is_dir():
        return []
    return [parse_entry(path.stem, path.read_text()) for path in sorted(directory.glob("*.md"))]


def write_entry(docs_root: Path, entry: Entry) -> None:
    directory = entries_dir(docs_root)
    directory.mkdir(parents=True, exist_ok=True)
    (directory / f"{entry.slug}.md").write_text(render_entry(entry))


def find_by_key(entries: List[Entry], key: Tuple[str, ...]) -> Optional[Entry]:
    return next((entry for entry in entries if entry.key == key), None)


def fingerprint_key(args: argparse.Namespace) -> Tuple[str, ...]:
    return (args.category, args.failure_mode, args.asset_path, args.asset_section)


def related_slugs(entries: List[Entry], args: argparse.Namespace) -> List[str]:
    if args.asset_path == NO_ASSET:
        return []
    key = fingerprint_key(args)
    return [e.slug for e in entries if e.fields.get("asset_path") == args.asset_path and e.key != key]


def command_match(args: argparse.Namespace) -> int:
    entries = load_entries(args.docs_root)
    same = find_by_key(entries, fingerprint_key(args))
    if same:
        print(f"match: {same.slug}")
        return EXIT_OK
    related = related_slugs(entries, args)
    print(f"related: {','.join(related)}" if related else "new")
    return EXIT_OK


def today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def amend_entry(args: argparse.Namespace) -> None:
    entry = next((e for e in load_entries(args.docs_root) if e.slug == args.slug), None)
    if entry is None:
        raise ToolError(f"no entry '{args.slug}' to amend")
    if not args.fix_pr and not args.fixed_by:
        raise ToolError("amend needs fix fields or --fix-pr; a new occurrence needs the fingerprint and --spec")
    apply_fix_fields(entry, args)
    if args.fix_pr:
        if entry.fields.get("status") != STATUS_FIXED:
            raise ToolError(f"entry '{args.slug}' is not fixed; --fix-pr applies to a fixed entry")
        entry.fields["fix_pr"] = args.fix_pr
    write_entry(args.docs_root, entry)


def apply_fix_fields(entry: Entry, args: argparse.Namespace) -> None:
    given = {name: getattr(args, name) for name in FIX_FIELDS if getattr(args, name)}
    if not given:
        return
    missing = [name for name in FIX_FIELDS if name not in given]
    if missing:
        raise ToolError(f"fix fields must be given together; missing: {', '.join(missing)}")
    entry.fields.update(given)
    entry.fields["status"] = STATUS_FIXED


def build_occurrence(args: argparse.Namespace) -> Dict[str, str]:
    return {
        "spec": args.spec,
        "increment": str(args.increment),
        "date": args.date or today(),
        "evidence": args.evidence or "",
        "discarded_by": args.discarded_by or "",
        "related_to": args.related_to or "",
        "related_reason": args.related_reason or "",
    }


def upsert_occurrence(entry: Entry, occurrence: Dict[str, str]) -> None:
    for index, existing in enumerate(entry.occurrences):
        if (existing.get("spec"), existing.get("increment")) == (occurrence["spec"], occurrence["increment"]):
            entry.occurrences[index] = occurrence
            return
    entry.occurrences.append(occurrence)


def require_record_args(args: argparse.Namespace) -> None:
    required = KEY_FIELDS + ("symptom", "spec", "increment")
    missing = [name for name in required if getattr(args, name) in (None, "")]
    if missing:
        raise ToolError(f"record needs: {', '.join('--' + name.replace('_', '-') for name in missing)}")
    if not SLUG_RE.match(args.slug):
        raise ToolError(f"invalid slug '{args.slug}': lowercase words joined by '-'")
    if args.date and not DATE_RE.match(args.date):
        raise ToolError(f"invalid date '{args.date}': expected YYYY-MM-DD")


def new_entry(args: argparse.Namespace, entries: List[Entry]) -> Entry:
    if any(e.slug == args.slug for e in entries):
        raise ToolError(f"slug '{args.slug}' already belongs to another match key")
    entry = Entry(args.slug)
    entry.fields.update({name: getattr(args, name) for name in KEY_FIELDS})
    entry.fields.update({"symptom": args.symptom, "status": STATUS_DETECTED})
    if args.backfilled:
        entry.fields["backfilled"] = "true"
    return entry


def command_record(args: argparse.Namespace) -> int:
    if not args.category and not args.spec:
        amend_entry(args)
        return EXIT_OK
    require_record_args(args)
    validate_vocabulary(args.category, args.failure_mode)
    entries = load_entries(args.docs_root)
    entry = find_by_key(entries, fingerprint_key(args))
    if entry is None:
        entry = new_entry(args, entries)
    apply_fix_fields(entry, args)
    if args.fix_pr:
        entry.fields["fix_pr"] = args.fix_pr
    upsert_occurrence(entry, build_occurrence(args))
    write_entry(args.docs_root, entry)
    print(f"recorded: {entry.slug}")
    return EXIT_OK


def dates_of(entry: Entry) -> List[str]:
    return [o["date"] for o in entry.occurrences if o.get("date")]


def display_status(entry: Entry) -> str:
    status = entry.fields.get("status", "")
    fixed_at = entry.fields.get("fixed_at", "")
    if status == STATUS_FIXED and any(date > fixed_at for date in dates_of(entry)):
        return STATUS_RECURRED
    return status


def cell(value: str) -> str:
    return value.replace("|", "\\|")


def index_cells(entry: Entry) -> List[str]:
    fields = entry.fields
    target = fields.get("fix_target") or f"{fields.get('asset_path', '')}#{fields.get('asset_section', '')}"
    dates = dates_of(entry)
    cells = [
        f"[{entry.slug}](entries/{entry.slug}.md)",
        fields.get("category", ""),
        fields.get("failure_mode", ""),
        target,
        display_status(entry),
        str(len(entry.occurrences)),
        max(dates) if dates else "",
    ]
    return [cell(c) for c in cells]


def render_index(entries: List[Entry]) -> str:
    rows = [index_cells(entry) for entry in sorted(entries, key=lambda e: e.slug)]
    widths = [
        max([len(INDEX_COLUMNS[i]), MIN_COLUMN_WIDTH] + [len(row[i]) for row in rows])
        for i in range(len(INDEX_COLUMNS))
    ]

    def line(cells: List[str]) -> str:
        return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, widths)) + " |\n"

    separator = ["-" * w for w in widths]
    return INDEX_TITLE + line(list(INDEX_COLUMNS)) + line(separator) + "".join(line(row) for row in rows)


def command_index(args: argparse.Namespace) -> int:
    args.docs_root.mkdir(parents=True, exist_ok=True)
    (args.docs_root / "INDEX.md").write_text(render_index(load_entries(args.docs_root)))
    return EXIT_OK


def occurrence_problems(entry: Entry) -> List[str]:
    name = f"entries/{entry.slug}.md"
    if not entry.occurrences:
        return [f"{name}: no occurrence under '## Occurrences'"]
    problems: List[str] = []
    for occurrence in entry.occurrences:
        problems += [f"{name}: occurrence missing '{f}'" for f in OCCURRENCE_REQUIRED if not occurrence.get(f)]
        if occurrence.get("date") and not DATE_RE.match(occurrence["date"]):
            problems.append(f"{name}: occurrence date '{occurrence['date']}' is not YYYY-MM-DD")
    return problems


def entry_problems(entry: Entry) -> List[str]:
    name = f"entries/{entry.slug}.md"
    problems = [f"{name}: missing required field '{f}'" for f in REQUIRED_FIELDS if not entry.fields.get(f)]
    category, mode = entry.fields.get("category", ""), entry.fields.get("failure_mode", "")
    if category and mode:
        try:
            validate_vocabulary(category, mode)
        except ToolError as error:
            problems.append(f"{name}: {error}")
    status = entry.fields.get("status", "")
    if status and status not in STATUSES:
        problems.append(f"{name}: invalid status '{status}'; allowed: {', '.join(STATUSES)}")
    if status == STATUS_FIXED:
        problems += [f"{name}: fixed entry missing '{f}'" for f in FIX_FIELDS if not entry.fields.get(f)]
    return problems + occurrence_problems(entry)


def duplicate_key_problems(entries: List[Entry]) -> List[str]:
    by_key: Dict[Tuple[str, ...], List[str]] = {}
    for entry in entries:
        if all(entry.key):
            by_key.setdefault(entry.key, []).append(f"entries/{entry.slug}.md")
    return [
        f"{' and '.join(files)} share the match key {' / '.join(key)}"
        for key, files in by_key.items()
        if len(files) > 1
    ]


def index_problems(docs_root: Path, entries: List[Entry]) -> List[str]:
    index_file = docs_root / "INDEX.md"
    current = index_file.read_text() if index_file.is_file() else None
    if current == render_index(entries):
        return []
    return ["INDEX.md is out of date; run `python3 .agents/scripts/learnings.py index` to regenerate it"]


def command_check(args: argparse.Namespace) -> int:
    entries = load_entries(args.docs_root)
    problems = [p for entry in entries for p in entry_problems(entry)]
    problems += duplicate_key_problems(entries) + index_problems(args.docs_root, entries)
    for problem in problems:
        print(problem, file=sys.stderr)
    return EXIT_PROBLEMS if problems else EXIT_OK


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Learning history tool")
    commands = parser.add_subparsers(dest="command", required=True)

    def add(name: str, handler) -> argparse.ArgumentParser:
        sub = commands.add_parser(name)
        sub.add_argument("--docs-root", type=Path, default=DEFAULT_DOCS_ROOT)
        sub.set_defaults(handler=handler)
        return sub

    for name, handler in (("match", command_match), ("record", command_record)):
        sub = add(name, handler)
        for option in ("category", "failure-mode", "asset-path", "asset-section"):
            sub.add_argument(f"--{option}", required=name == "match")
    record = commands.choices["record"]
    for option in (
        "slug", "symptom", "spec", "date", "evidence", "discarded-by", "related-to", "related-reason",
        "fixed-by", "fix-target", "fix-why", "fixed-at", "fix-pr",
    ):
        record.add_argument(f"--{option}", required=option == "slug")
    record.add_argument("--increment", type=int)
    record.add_argument("--backfilled", action="store_true")
    add("index", command_index)
    add("check", command_check)
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.handler(args)
    except ToolError as error:
        print(f"error: {error}", file=sys.stderr)
        return EXIT_PROBLEMS


if __name__ == "__main__":
    sys.exit(main())
